# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_ABROLHOS)		+= abrolhos.o
ccflags-y			+= -DCONFIG_EDGETPU_TELEMETRY_TRACE=1 -DCONFIG_ABROLHOS=1
ccflags-y			+= -I$(srctree)/vendor-stub-include
ccflags-y			+= -DGIT_REPO_TAG=\"in-tree\"

edgetpu-objs	:= edgetpu-mailbox.o edgetpu-telemetry.o edgetpu-mapping.o edgetpu-dmabuf.o edgetpu-async.o edgetpu-iremap-pool.o edgetpu-sw-watchdog.o edgetpu-firmware.o edgetpu-firmware-util.o edgetpu-domain-pool.o

mobile-objs	:= edgetpu-kci.o

abrolhos-y	:= abrolhos-device.o abrolhos-device-group.o abrolhos-fs.o abrolhos-core.o abrolhos-platform.o abrolhos-firmware.o abrolhos-thermal.o abrolhos-pm.o abrolhos-iommu.o abrolhos-usage-stats.o abrolhos-wakelock.o $(mobile-objs) $(edgetpu-objs)

CFLAGS_abrolhos-fs.o := -I$(src)/include
