# SPDX-License-Identifier: GPL-2.0

ccflags-y += -I$(srctree)/aoc
ccflags-y += -I$(srctree)/aoc_ipc
ccflags-y += -I$(srctree)/vendor-stub-include
ccflags-y += -I$(srctree)/sound/usb
ccflags-y += -DCONFIG_SOC_GS101=1

obj-$(CONFIG_AOC_DRIVER)	+= aoc_alsa_dev.o
obj-$(CONFIG_AOC_DRIVER)	+= aoc_alsa_dev_util.o
aoc_alsa_dev_util-objs		:= aoc_alsa_path.o aoc_alsa_drv.o \
				   aoc_alsa_pcm.o aoc_alsa_voice.o \
				   aoc_alsa_compr.o aoc_alsa_ctl.o aoc_alsa_hw.o \
				   aoc_alsa_nohost.o aoc_alsa_incall.o aoc_alsa_voip.o
aoc_alsa_dev-objs		:= aoc_alsa_card.o
